it.only('visit and login' , function(){
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
    cy.wait(500);
    cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('Admin', { delay: 100 });
    cy.wait(500);
    cy.get(':nth-child(3) > .oxd-input-group > :nth-child(2) > .oxd-input').type('admin123', { delay: 100 });
    cy.wait(500);
    cy.get('.oxd-button').click();
    cy.wait(500);
    cy.get(':nth-child(6) > .oxd-main-menu-item').click();
    cy.wait(500);
    cy.get('.--name-grouped-field > :nth-child(1) > :nth-child(2) > .oxd-input').clear();
    cy.wait(500);
    cy.get('.--name-grouped-field > :nth-child(2) > :nth-child(2) > .oxd-input').clear();
    cy.wait(500);
    cy.get('.--name-grouped-field > :nth-child(3) > :nth-child(2) > .oxd-input').clear();
    cy.wait(500);
    cy.get(':nth-child(1) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').clear();
    cy.wait(500);
    cy.get(':nth-child(2) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').clear();
    cy.wait(500);
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').clear();
    cy.wait(500);
    cy.get(':nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-date-wrapper > .oxd-date-input > .oxd-icon').click();
    cy.wait(500);
    cy.get(':nth-child(10) > .oxd-calendar-date').click();
    cy.wait(500);
    cy.get('.--name-grouped-field > :nth-child(1) > :nth-child(2) > .oxd-input').type('Abdulaziz', { delay: 100 });
    cy.wait(500);
    cy.get(':nth-child(2) > :nth-child(2) > .oxd-input').type('Mohammed', { delay: 100 });
    cy.wait(500);
    cy.get(':nth-child(3) > :nth-child(2) > .oxd-input').type('Alkhlaiwe', { delay: 100 });
    cy.wait(500);
    cy.get(':nth-child(1) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('1111111111', { delay: 100 });
    cy.wait(500);
    cy.get(':nth-child(3) > :nth-child(1) > :nth-child(2) > .oxd-input-group > :nth-child(2) > .oxd-input').type('0000000000', { delay: 100 });
    cy.wait(500);
    cy.get(':nth-child(2) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-input').type('2222222222', { delay: 100 });
    cy.wait(500);
    cy.get(':nth-child(5) > :nth-child(1) > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
    cy.wait(500);
    cy.get(':nth-child(154)').click();
    cy.wait(500);
    cy.get('.orangehrm-card-container > .oxd-form > .oxd-form-row > .oxd-grid-3 > :nth-child(1) > .oxd-input-group > :nth-child(2) > .oxd-select-wrapper > .oxd-select-text > .oxd-select-text--after > .oxd-icon').click();
    cy.wait(500);
    cy.get('.oxd-select-dropdown > :nth-child(2)').click();
    cy.wait(500);
    cy.get(':nth-child(1) > .oxd-form > .oxd-form-actions > .oxd-button').click();
    cy.wait(500);
    cy.get('.orangehrm-card-container > .oxd-form > .oxd-form-actions > .oxd-button').click();
    cy.wait(500);
    cy.get('.employee-image').click();
    cy.wait(500);
    cy.get('.oxd-file-div > .oxd-icon-button').click();
    cy.wait(500);
    cy.get('input[type="file"]').selectFile('cypress/fixtures/profilepic.jpg', { force: true });
    cy.wait(500);
    cy.get('.oxd-button').click();
    cy.wait(500);
    cy.get(':nth-child(8) > .oxd-main-menu-item').click();
    cy.wait(500);

});